# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookdit', '0002_auto_20160326_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userextend',
            new_name='userprofile',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeend',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 22, 17, 21, 895856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timestart',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 22, 17, 21, 895821, tzinfo=utc)),
        ),
    ]
