# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookdit', '0003_auto_20160327_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.IntegerField(default=1)),
                ('timestart', models.DateTimeField(default=datetime.datetime(2016, 3, 28, 23, 53, 28, 312179, tzinfo=utc))),
                ('timeend', models.DateTimeField(default=datetime.datetime(2016, 3, 28, 23, 53, 28, 312219, tzinfo=utc))),
                ('available', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule2user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeend',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 28, 23, 53, 28, 311099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timestart',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 28, 23, 53, 28, 311052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2vendor', to='bookdit.vendor'),
        ),
    ]
